"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/sidebar";
import { usePathname } from "next/navigation";
import { StoreProvider } from "@/redux/store/StoreProvider";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: 'Control Tower',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const pathname = usePathname();
  // console.log('pathname', pathname)
  const disabledSidebar = ["/login"];
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex h-screen border-collapse overflow-hidden">
            {!disabledSidebar.includes(pathname) && <Sidebar />}
            <main className="flex-1 overflow-y-auto overflow-x-hidden pt-16 bg-secondary/10 pb-1">
              {children}
            </main>
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
